import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// 1. Importe o componente Header aqui
import Header from "@/components/Header"; 

import "./globals.css";
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 2. Coloque o componente Header antes de 'children' */}
        <Header /> 
        
        {/* 'children' é onde o conteúdo específico da página (home, admin) será renderizado */}
        {children}
      </body>
    </html>
  );
}